---
- name: "Update"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "delete outdated dependencies"
  become: true
  apt:
    autoremove: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Install npm
  become: true
  apt:
    name: npm
    state: present

- name: Install pm2 globally
  become: true
  npm:
    name: pm2
    state: present
    global: yes

- name: "Start application"
  shell: |
    cd ~/backend-app
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: execute_node

